"""
ingest_funds.py — Build a FAISS vector store from scraped fund data.

Takes the text documents generated by scrape_scheme_details.py
and creates a multi-fund FAISS index for RAG querying.

Also supports ingesting SID PDFs from data/sids/ directory.

Run:  python -m scripts.ingest_funds
"""

import sys
import os
import glob
import time

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from langchain_core.documents import Document
from src.config import VECTORSTORE_DIR, SIDS_DIR, EMBEDDING_MODEL
from src.embeddings import get_embedding_model
from src.database import init_database, get_fund_by_code


def load_fund_texts(texts_dir: str = "data/fund_texts") -> list[Document]:
    """
    Load text documents generated by the scheme details scraper.
    Each .txt file becomes one or more LangChain Documents with metadata.
    """
    documents = []

    if not os.path.exists(texts_dir):
        print(f"⚠️ Directory {texts_dir} not found. Run scrape_scheme_details.py first.")
        return documents

    txt_files = glob.glob(os.path.join(texts_dir, "*.txt"))
    print(f"📄 Found {len(txt_files)} fund text files in {texts_dir}/")

    for filepath in txt_files:
        # Extract scheme code from filename (e.g., "120503.txt" -> 120503)
        filename = os.path.basename(filepath)
        scheme_code_str = filename.replace(".txt", "")

        try:
            scheme_code = int(scheme_code_str)
        except ValueError:
            scheme_code = None

        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read().strip()

        if not content:
            continue

        # Get fund info from database for metadata
        fund_info = None
        if scheme_code:
            fund_info = get_fund_by_code(scheme_code)

        fund_name = fund_info["scheme_name"] if fund_info else filename
        fund_house = fund_info["fund_house"] if fund_info else "Unknown"

        # Create document with rich metadata
        doc = Document(
            page_content=content,
            metadata={
                "source": filepath,
                "fund_name": fund_name,
                "fund_house": fund_house,
                "scheme_code": scheme_code,
                "type": "fund_data",
                "page": 1,
            }
        )
        documents.append(doc)

    return documents


def load_sid_pdfs(sids_dir: str = None) -> list[Document]:
    """
    Load and parse SID PDFs from the sids directory.
    Returns chunked documents with metadata.
    """
    sids_dir = sids_dir or SIDS_DIR
    documents = []

    if not os.path.exists(sids_dir):
        print(f"ℹ️ SIDs directory {sids_dir} not found. Skipping PDF ingestion.")
        return documents

    pdf_files = glob.glob(os.path.join(sids_dir, "*.pdf"))
    print(f"📄 Found {len(pdf_files)} SID PDFs in {sids_dir}/")

    for pdf_path in pdf_files:
        filename = os.path.basename(pdf_path)
        fund_name = filename.replace(".pdf", "").replace("_", " ").strip()

        print(f"   📖 Parsing: {filename}")
        try:
            from src.pdf_parser import parse_pdf
            from src.chunker import create_chunks

            parsed_pages = parse_pdf(pdf_path)
            chunks = create_chunks(parsed_pages, filename)

            # Tag each chunk with fund metadata
            for chunk in chunks:
                chunk.metadata["fund_name"] = fund_name
                chunk.metadata["fund_house"] = "Unknown (SID)"
                chunk.metadata["type"] = "sid_document"

            documents.extend(chunks)
            print(f"      ✅ {len(chunks)} chunks created")

        except Exception as e:
            print(f"      ❌ Error parsing {filename}: {e}")

    return documents


def chunk_fund_texts(documents: list[Document], chunk_size: int = 800, chunk_overlap: int = 150) -> list[Document]:
    """
    Chunk fund text documents into smaller pieces for better retrieval.
    Fund texts are already structured, so we use a smaller chunk size.
    """
    from langchain_text_splitters import RecursiveCharacterTextSplitter

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap,
        separators=["\n\n", "\n", ". ", " ", ""],
    )

    chunked = []
    for doc in documents:
        splits = splitter.split_documents([doc])
        # Preserve original metadata in each chunk
        for i, split in enumerate(splits):
            split.metadata.update(doc.metadata)
            split.metadata["chunk_index"] = i
        chunked.extend(splits)

    return chunked


def build_vectorstore(documents: list[Document]):
    """Build and save the FAISS vector store."""
    from langchain_community.vectorstores import FAISS
    import shutil

    if not documents:
        print("⚠️ No documents to index. Run the scrapers first.")
        return

    print(f"\n🧠 Building FAISS vector store with {len(documents)} chunks...")

    # Get embedding model
    embeddings = get_embedding_model()

    # Clear old vectorstore
    if os.path.exists(VECTORSTORE_DIR):
        shutil.rmtree(VECTORSTORE_DIR)

    # Create FAISS index
    vectorstore = FAISS.from_documents(
        documents=documents,
        embedding=embeddings,
    )

    # Save to disk
    vectorstore.save_local(VECTORSTORE_DIR)

    print(f"✅ Vector store saved to {VECTORSTORE_DIR}/")
    print(f"   Total chunks indexed: {len(documents)}")

    # Print stats
    fund_names = set(d.metadata.get("fund_name", "Unknown") for d in documents)
    fund_houses = set(d.metadata.get("fund_house", "Unknown") for d in documents)
    print(f"   Unique funds: {len(fund_names)}")
    print(f"   Unique AMCs: {len(fund_houses)}")

    return vectorstore


def main():
    """Main ingestion pipeline."""
    import argparse
    parser = argparse.ArgumentParser(description="Ingest fund data into FAISS vector store")
    parser.add_argument("--texts-only", action="store_true",
                        help="Only ingest text files (skip SID PDFs)")
    parser.add_argument("--pdfs-only", action="store_true",
                        help="Only ingest SID PDFs (skip text files)")
    args = parser.parse_args()

    start = time.time()

    print("=" * 60)
    print("📦 Fund Data Ingestion — Building Vector Store")
    print("=" * 60)

    init_database()

    all_documents = []

    # Load fund text documents
    if not args.pdfs_only:
        fund_docs = load_fund_texts()
        if fund_docs:
            chunked_fund_docs = chunk_fund_texts(fund_docs)
            print(f"   Chunked {len(fund_docs)} fund texts -> {len(chunked_fund_docs)} chunks")
            all_documents.extend(chunked_fund_docs)

    # Load fund manager profiles
    if not args.pdfs_only:
        manager_docs = load_fund_texts("data/manager_profiles")
        if manager_docs:
            # Tag as manager profiles
            for doc in manager_docs:
                doc.metadata["type"] = "manager_profile"
            chunked_mgr_docs = chunk_fund_texts(manager_docs, chunk_size=600, chunk_overlap=100)
            print(f"   Chunked {len(manager_docs)} manager profiles -> {len(chunked_mgr_docs)} chunks")
            all_documents.extend(chunked_mgr_docs)

    # Load SID PDFs
    if not args.texts_only:
        sid_docs = load_sid_pdfs()
        all_documents.extend(sid_docs)

    # Build vector store
    if all_documents:
        build_vectorstore(all_documents)
    else:
        print("\nNo documents found to ingest!")
        print("   Run these commands first:")
        print("   1. python -m scripts.scrape_nav")
        print("   2. python -m scripts.scrape_scheme_details --limit 100")
        print("   3. python -m scripts.scrape_fund_managers --limit 100")
        print("   4. python -m scripts.ingest_funds")

    elapsed = time.time() - start
    print(f"\n⏱️  Completed in {elapsed:.1f} seconds")


if __name__ == "__main__":
    main()
